# Generated by Django 4.2.20 on 2025-08-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={
                "ordering": ["-id"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.RenameIndex(
            model_name="users",
            new_name="person_is_acti_9b83d5_idx",
            old_name="person_user_is_acti_26067e_idx",
        ),
        migrations.AddField(
            model_name="users",
            name="category",
            field=models.CharField(
                choices=[
                    ("BASE", "Employee"),
                    ("DRIVER", "Truck driver"),
                    ("MANAGER", "Manager"),
                    ("CLIENT", "Client"),
                    ("ADMIN", "Supervisor"),
                ],
                default="BASE",
                max_length=50,
            ),
        ),
        migrations.AlterModelTable(
            name="users",
            table="person",
        ),
    ]
